# -*- coding: utf-8 -*-
"""SINQ_quantization

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aSefnet0Rn9DnST5mkAULp4W1YlSnpIR

# OpenVLA 4-bit Quantization with SINQ

This script quantizes OpenVLA-7B to 4-bit using SINQ
and saves it to Google Drive for LIBERO benchmarking
"""

!pip install transformers==4.38.2
!pip install torch torchvision accelerate
!pip install git+https://github.com/huawei-csl/SINQ.git  # Install SINQ from source
!pip install safetensors
!pip install timm==0.9.16

from google.colab import drive
drive.mount('/content/drive')

# #Grab Layer data -- DON'T NEED TO RUN THIS CELL ANYMORE

# from transformers import AutoModelForVision2Seq

# vla_model = "openvla/openvla-7b-finetuned-libero-spatial"

# model = AutoModelForVision2Seq.from_pretrained(
#     vla_model,
#     torch_dtype="auto",
#     device_map="cpu",
#     trust_remote_code=True
# )


# for name, _ in model.named_modules():
#     # if "llama" in name.lower() or "model" in name:
#         print(name)

import torch
import os
import json
import warnings
warnings.filterwarnings('ignore')

# Load with compatible transformers version
from transformers import AutoTokenizer, AutoModelForVision2Seq

#sinq imports
from sinq.sinqlinear import sinq_base_quant_config
from sinq.patch_model import AutoSINQHFModel

#PATHS
vla_model = "openvla/openvla-7b-finetuned-libero-spatial"

# Create directory for quantized model
SAVE_DIR = "/content/drive/MyDrive/openvlaa/technical/openvla_4bit_sinq"
os.makedirs(SAVE_DIR, exist_ok=True)
print(f"Quantized model will be saved to: {SAVE_DIR}")

"""#Need to patch get_ignore_layers to only quantize the llama layers
VLA structure:
- vision_backbone.*
- projector.*
- language_model.model.layers.*
- language_model.model.embed_tokens
- language_model.lm_head
"""

import sinq.utils
from sinq.utils import get_ignore_layers

def get_ignore_layers_openvla(model):
    ignore_layers = []

    for name, module in model.named_modules():

        # Only allow quantization for LLaMA transformer blocks
        if name.startswith("language_model.model.layers"):
            continue

        # Everything else should be ignored
        ignore_layers.append(name)

    return ignore_layers

#Replace the attribute get_ignore_layers in the sinq.utils module
#with my function get_ignore_layers_openvla

sinq.utils.get_ignore_layers = get_ignore_layers_openvla

"""#Quantize using SINQ"""

print("Loading tokenizer...")
tokenizer = AutoTokenizer.from_pretrained(vla_model, trust_remote_code=True)

print("Loading model")
model = AutoModelForVision2Seq.from_pretrained(
    vla_model,
    torch_dtype=torch.bfloat16,
    device_map="auto",
    trust_remote_code=True
)

# Create quantization config using the correct function signature
# sinq_base_quant_config returns a dictionary, not an object
quant_cfg = sinq_base_quant_config(
            nbits=4,            # 4-bit quantization
            group_size=64,      # Group size for quantization
            tiling_mode="1D",   # Tiling strategy
            method="sinq",      # Quantization method (will be remapped to sinq_quantAux)
            quant_zero=False,   # Don't quantize zero points
            quant_scale=False   # Don't quantize scales
        )
print("Quantization config created:")
print(json.dumps(quant_cfg, indent=2))

# # ==============================================
# #  Quantization Configuration
# # ==============================================

# # Create SINQ quantization config
# quant_cfg = BaseQuantizeConfig(
#     nbits=4,            # 4-bit quantization
#     group_size=64,      # Group size for quantization
#     tiling_mode="1D",   # Tiling strategy
#     method="sinq",      # Quantization method
# )

print("Quantization config created:")

# Apply quantization
qmodel = AutoSINQHFModel.quantize_model(
    model,
    tokenizer=tokenizer,
    quant_config=quant_cfg,
    compute_dtype=torch.bfloat16,
    device=model.device,  # SINQ standalone should support this
)

print("✓ Model quantized with SINQ (standalone mode)")

# Save using SINQ's standalone save function

print(f"\nSaving quantized model to {SAVE_DIR}...")

AutoSINQHFModel.save_quantized_safetensors(
    qmodel,
    tokenizer,
    SAVE_DIR,
    verbose=True,
    max_shard_size="5GB"
)

print("✓ Model saved successfully!")

print("\nVerifying quantization...")

quantized_layers = []

for name, module in qmodel.named_modules():
    if "SINQ" in module.__class__.__name__:
        quantized_layers.append(name)

print("Total quantized layers:", len(quantized_layers))

for l in quantized_layers[:30]:
    print(l)

"""
Note:
the expected output:
language_model.model.layers.0.self_attn.q_proj
language_model.model.layers.0.self_attn.k_proj
language_model.model.layers.0.self_attn.v_proj
language_model.model.layers.0.self_attn.o_proj
language_model.model.layers.0.mlp.gate_proj
language_model.model.layers.0.mlp.up_proj
language_model.model.layers.0.mlp.down_proj
...

we shouldn't see:
vision_backbone
projector
embed_tokens
lm_head
"""

# Check memory reduction
def calculate_memory(model):
    total_params = sum(p.numel() for p in model.parameters())
    quantized_size = 0
    full_size = 0

    for name, param in model.named_parameters():
        if param.dtype == torch.uint8:
            quantized_size += param.numel() * 0.5  # 4-bit = 0.5 bytes per param
        else:
            full_size += param.numel() * 2  # bfloat16 = 2 bytes per param

    total_bytes = quantized_size + full_size
    return total_params, total_bytes / (1024**3)

total_params, memory_gb = calculate_memory(qmodel)
baseline_gb = total_params * 2 / (1024**3)

print(f"Total parameters: {total_params:,}")
print(f"Quantized memory: {memory_gb:.2f} GB")
print(f"Baseline (FP16): {baseline_gb:.2f} GB")
print(f"Memory reduction: {(1 - memory_gb / baseline_gb) * 100:.1f}%")

# ==============================================
# Memory Usage Statistics
# ==============================================

def get_model_size_mb(model):
    """Calculate model size in MB"""
    param_size = 0
    buffer_size = 0

    for param in model.parameters():
        param_size += param.nelement() * param.element_size()

    for buffer in model.buffers():
        buffer_size += buffer.nelement() * buffer.element_size()

    size_mb = (param_size + buffer_size) / 1024 / 1024
    return size_mb

original_size = 7000  # Approximate size of OpenVLA-7B in MB
quantized_size = get_model_size_mb(model)
compression_ratio = original_size / quantized_size

print(f"\n📈 Quantization Results:")
print(f"Original model size: ~{original_size} MB")
print(f"Quantized model size: {quantized_size:.1f} MB")
print(f"Compression ratio: {compression_ratio:.1f}x")
print(f"Memory reduction: {(1 - quantized_size/original_size)*100:.1f}%")