# -*- coding: utf-8 -*-
"""SINQ_quantization

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aSefnet0Rn9DnST5mkAULp4W1YlSnpIR

# OpenVLA 4-bit Quantization with SINQ

This script quantizes OpenVLA-7B to 4-bit using SINQ
and saves it to Google Drive for LIBERO benchmarking
"""

from google.colab import drive
drive.mount('/content/drive')

# Create directory for quantized model
import os
quantized_model_path = "/content/drive/MyDrive/openvla_4bit_sinq"
os.makedirs(quantized_model_path, exist_ok=True)
print(f"Quantized model will be saved to: {quantized_model_path}")

!pip install transformers==4.38.2
!pip install torch torchvision accelerate
!pip install git+https://github.com/huawei-csl/SINQ.git  # Install SINQ from source
!pip install safetensors
!pip install timm==0.9.16

# #Grab Layer data

# from transformers import AutoModelForVision2Seq

# model_name = "openvla/openvla-7b-finetuned-libero-spatial"

# model = AutoModelForVision2Seq.from_pretrained(
#     model_name,
#     torch_dtype="auto",
#     device_map="cpu",
#     trust_remote_code=True
# )


# for name, _ in model.named_modules():
#     # if "llama" in name.lower() or "model" in name:
#         print(name)

import torch
import warnings
warnings.filterwarnings('ignore')

# Load with compatible transformers version
from transformers import AutoTokenizer, AutoModelForVision2Seq

#sinq imports
from sinq.sinqlinear import sinq_base_quant_config
from sinq.patch_model import AutoSINQHFModel

MODEL_NAME = "openvla/openvla-7b-finetuned-libero-spatial"

print("Loading tokenizer...")
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, trust_remote_code=True)

print("Loading model (this requires transformers 4.38.2)...")
model = AutoModelForVision2Seq.from_pretrained(
    MODEL_NAME,
    torch_dtype=torch.bfloat16,
    device_map="auto",
    trust_remote_code=True
)

# Create quantization config using the correct function signature
# sinq_base_quant_config returns a dictionary, not an object
quant_cfg = sinq_base_quant_config(
            nbits=4,            # 4-bit quantization
            group_size=64,      # Group size for quantization
            tiling_mode="1D",   # Tiling strategy
            method="sinq",      # Quantization method (will be remapped to sinq_quantAux)
            quant_zero=False,   # Don't quantize zero points
            quant_scale=False   # Don't quantize scales
        )
print("Quantization config created:")
print(json.dumps(quant_cfg, indent=2))

# ==============================================
#  Quantization Configuration
# ==============================================

# Create SINQ quantization config (standalone version)
quant_cfg = BaseQuantizeConfig(
    nbits=4,            # 4-bit quantization
    group_size=64,      # Group size for quantization
    tiling_mode="1D",   # Tiling strategy
    method="sinq",      # Quantization method
    # Specify modules to exclude from quantization
    modules_to_exclude = [
      "lm_head",
      "embed_tokens",
      "vision_backbone",
      "vision_backbone.model",
      "projector"]
)

# Apply quantization
qmodel = AutoSINQHFModel.quantize_model(
    model,
    tokenizer=tokenizer,
    quant_config=quant_cfg,
    compute_dtype=torch.bfloat16,
    device=model.device,  # SINQ standalone should support this
)

print("✓ Model quantized with SINQ (standalone mode)")

print("\nVerifying quantization...")

# Check memory reduction
def calculate_memory(model):
    total_params = sum(p.numel() for p in model.parameters())
    quantized_size = 0
    full_size = 0

    for name, param in model.named_parameters():
        if param.dtype == torch.uint8:
            quantized_size += param.numel() * 0.5  # 4-bit = 0.5 bytes per param
        else:
            full_size += param.numel() * 2  # bfloat16 = 2 bytes per param

    total_bytes = quantized_size + full_size
    return total_params, total_bytes / (1024**3)

total_params, memory_gb = calculate_memory(qmodel)
baseline_gb = total_params * 2 / (1024**3)

print(f"Total parameters: {total_params:,}")
print(f"Quantized memory: {memory_gb:.2f} GB")
print(f"Baseline (FP16): {baseline_gb:.2f} GB")
print(f"Memory reduction: {(1 - memory_gb / baseline_gb) * 100:.1f}%")

# Save using SINQ's standalone save function
save_dir = "openvla-7b-libero-spatial-4bit-sinq"

print(f"\nSaving quantized model to {save_dir}...")
AutoSINQHFModel.save_quantized_safetensors(
    qmodel,
    tokenizer,
    save_dir,
    verbose=True,
    max_shard_size="5GB"
)

print("✓ Model saved successfully!")

# Configuration
MODEL_NAME = "openvla/openvla-7b-finetuned-libero-spatial"
QUANTIZATION_CONFIG = SinqConfig(
    nbits=4,                    # 4-bit quantization
    group_size=64,              # Group size for quantization
    tiling_mode="1D",         # Tiling strategy
    method="sinq",            # Quantization method
    modules_to_not_convert=[
    "lm_head",
    "embed_tokens",
    "vision_backbone",
    "vision_backbone.model",
    "projector"]
)

print("🎯 Starting OpenVLA 4-bit quantization with SINQ...")
print(f"Model: {MODEL_NAME}")
print(f"Quantization: {QUANTIZATION_CONFIG.nbits}-bit, group_size={QUANTIZATION_CONFIG.group_size}")

# ==============================================
# Memory Usage Statistics
# ==============================================

def get_model_size_mb(model):
    """Calculate model size in MB"""
    param_size = 0
    buffer_size = 0

    for param in model.parameters():
        param_size += param.nelement() * param.element_size()

    for buffer in model.buffers():
        buffer_size += buffer.nelement() * buffer.element_size()

    size_mb = (param_size + buffer_size) / 1024 / 1024
    return size_mb

original_size = 7000  # Approximate size of OpenVLA-7B in MB
quantized_size = get_model_size_mb(model)
compression_ratio = original_size / quantized_size

print(f"\n📈 Quantization Results:")
print(f"Original model size: ~{original_size} MB")
print(f"Quantized model size: {quantized_size:.1f} MB")
print(f"Compression ratio: {compression_ratio:.1f}x")
print(f"Memory reduction: {(1 - quantized_size/original_size)*100:.1f}%")